cannon 3
---

In [1]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('dark_background')
%matplotlib inline
import tensorflow as tf
import keras

Simulation function

In [2]:
pi = np.pi

#simulates a ballistic trajectory and returns the smallest distance to the target position
def simulate_trajectory_distance(speed, azi, pitch, target, origin = np.array([0.,0.,0.]), timestep = 0.1, g = -10.):
    #get cartesian velocity from spherical coordinates
    velocity = speed*np.array([
        np.cos(azi)*np.cos(pitch),
        np.sin(azi)*np.cos(pitch),
        np.sin(pitch)
    ])
#     print(f'Starting velocity {velocity}.')
    #make acceleration vector
    acc = np.array([0.,0., g])
    #record origin and first position after 1 timestep
    history = [origin, origin+ velocity*timestep + (1/2)*acc*timestep**2]
    position = history[-1]
#     print(history)
    #record distances
    distances = [np.linalg.norm(target - origin), np.linalg.norm(target - position)]
    #while the ball is above the ground, timestep to change position
    while position[2] >= 0:
#         print(history[-1])
        position = 2*history[-1] - history[-2] + acc*(timestep**2)
        distances.append(np.linalg.norm(target - position))
        history.append(position)
    return np.array(distances).min()
    

In [3]:
distance = simulate_trajectory_distance(100, 0, pi/3, np.array([100,200,300]))
distance

221.16372929942816

In [18]:
seed = 2022
rng = np.random.default_rng(seed)

#eps == 1.1920928955078125e-07
eps = np.finfo(np.float32).eps.item()

gamma = 0.99
rounds_per_load = 5
minimum_acceptible_score = 500
scores_to_average = 10
max_speed = 100 #m/s
field_size = 2000 #m

hit_distance = 5 #5m radius of target
#miss_penalty = 500 #add this distance as a penalty for missing
num_inputs = 3 #target x, y, z
num_outputs = 3 #speed/max_speed, azimuth/(2pi), pitch/(pi)(
num_hidden = 32

#make model
inputs = keras.layers.Input(shape = (num_inputs,))
dense_1 = keras.layers.Dense(num_hidden, activation = 'relu')(inputs)
outputs = keras.layers.Dense(num_outputs)(dense_1)
model = keras.Model(inputs = inputs, outputs = outputs)

#optimizer and loss function
optimizer = tf.optimizers.Adam(learning_rate = 0.01)
loss_fn = keras.losses.Huber()

avg_recent_score = 0
all_scores = [0]
total_loss = tf.constant(0.)

# model.trainable_variables[1] = tf.convert_to

while avg_recent_score < minimum_acceptible_score:
    with tf.GradientTape() as tape:
        command_history = []
        loss_history = []
        #reload the cannon and shoot all shots
        for shot in range(rounds_per_load):
            target = field_size*rng.random(3) - field_size/2
            target[2] = abs(target[2])
            target = tf.convert_to_tensor(target)
            target = tf.expand_dims(target, 0)
            
            command = model(target)
            speed, azi, pitch = command[0]
            speed = np.float32(speed*max_speed)
            azi = np.float32(azi*2*pi)
            pitch = np.float32(pitch*pi)
            
            loss = simulate_trajectory_distance(speed, azi, pitch, target, timestep = 0.5)
            loss = loss_fn([0], [loss])
            loss_history.append(loss)
            
        total_loss = sum(loss_history)
        grads = tape.gradient(total_loss, model.trainable_variables)
        
        print('got to optimizing')
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        
        all_scores.append(total_loss)
        loss_history.clear()
        avg_recent_score = np.mean(all_scores[-scores_to_average:])
        if len(all_scores[:-2])%100 == 0:
            print(f'finished with trial {len(all_scores[:-2])}')

got to optimizing


ValueError: No gradients provided for any variable: (['dense_12/kernel:0', 'dense_12/bias:0', 'dense_13/kernel:0', 'dense_13/bias:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'dense_12/kernel:0' shape=(3, 32) dtype=float32, numpy=
array([[-0.15404779, -0.38550666,  0.17879567, -0.17078783,  0.10806009,
        -0.19836852, -0.23261036, -0.23141365,  0.1755592 ,  0.23261878,
         0.24854323, -0.39840996,  0.02823347,  0.07722616, -0.01893526,
        -0.24670692, -0.11922294,  0.2161121 , -0.29501492, -0.20330444,
        -0.24229674, -0.03097439,  0.41262928, -0.382739  , -0.11801398,
         0.13302818,  0.19009063, -0.25516063,  0.29355344, -0.08093429,
         0.1984612 , -0.10413104],
       [-0.37951094,  0.1212146 , -0.2365709 ,  0.3531926 , -0.03570837,
        -0.27961355, -0.29321268,  0.03928804,  0.07237238,  0.31452605,
        -0.02526978, -0.25421143, -0.16888985,  0.19756696, -0.13244075,
        -0.16993947,  0.27660987, -0.15632346, -0.22930066,  0.00114805,
        -0.1097264 , -0.05406189, -0.19355124, -0.01258031,  0.29900053,
         0.06782329,  0.1317828 ,  0.04197517, -0.02784801, -0.37060547,
        -0.40225914, -0.37219882],
       [-0.25564831, -0.17656116, -0.17717369,  0.04280436,  0.13990417,
         0.04962495,  0.12629023, -0.3992727 , -0.3041325 ,  0.05853683,
         0.26148996, -0.06845438,  0.12679121, -0.26507545, -0.40516648,
         0.33432677,  0.08344579, -0.21144229, -0.3506884 ,  0.0192911 ,
         0.08101386,  0.01170391,  0.36254802, -0.3512729 , -0.25967684,
         0.35587624,  0.3424351 , -0.376309  , -0.3731922 , -0.12483951,
        -0.35300642,  0.00757012]], dtype=float32)>), (None, <tf.Variable 'dense_12/bias:0' shape=(32,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>), (None, <tf.Variable 'dense_13/kernel:0' shape=(32, 3) dtype=float32, numpy=
array([[ 0.2377747 ,  0.06882268,  0.387374  ],
       [ 0.21425721,  0.17830238,  0.35538903],
       [-0.26285803,  0.07655302, -0.40407658],
       [ 0.3669248 , -0.39127812,  0.06397343],
       [-0.37730318,  0.1101425 ,  0.31125268],
       [ 0.11660984,  0.07654643, -0.06719518],
       [ 0.3461034 , -0.01871353,  0.17144164],
       [-0.04115838,  0.35045436, -0.21380472],
       [-0.26269305,  0.29300085, -0.32261682],
       [ 0.3749464 , -0.3679705 , -0.00288385],
       [-0.04712433, -0.1821559 , -0.17440543],
       [-0.07817441, -0.28131133,  0.2021496 ],
       [ 0.21857038,  0.23637709, -0.15965667],
       [-0.4038438 , -0.31536525, -0.3739668 ],
       [-0.40525284,  0.08393046,  0.22487536],
       [ 0.30602375,  0.04196429, -0.1993222 ],
       [ 0.21929535,  0.30159137, -0.08979768],
       [ 0.26951417,  0.29661873,  0.40079758],
       [ 0.11747679, -0.02387425,  0.10531422],
       [ 0.10068443,  0.15969923, -0.01148406],
       [ 0.33112827,  0.15520188,  0.15013883],
       [ 0.38781872, -0.00183481,  0.39933118],
       [-0.22809772,  0.12821385,  0.3944203 ],
       [ 0.24631593, -0.3758723 ,  0.18676797],
       [-0.15594894, -0.07714057, -0.13252968],
       [ 0.20709369,  0.18852863,  0.10351971],
       [ 0.17085138,  0.27892086, -0.3320188 ],
       [ 0.18210271,  0.00255731,  0.09128955],
       [ 0.2808145 ,  0.26245084,  0.06991744],
       [ 0.14541987, -0.29612812,  0.14283922],
       [-0.17421333, -0.34766972, -0.24903312],
       [-0.25620672,  0.00083819, -0.27402532]], dtype=float32)>), (None, <tf.Variable 'dense_13/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>)).

In [16]:
loss_fn()